### PR TITLE
previews: mymattress flow

### PR DESCRIPTION
**Pull request by reez**
https://www.figma.com/file/VB3GQdAnhl8yta44DY3PSV/Bitcoin-Wallet-UI-Kit?node-id=812%3A0

### CODE REVIEW

**Comment by reez** [comment]
mm-onboarding

**Comment by reez** [comment]
mm-home

**Comment by reez** [comment]
mm-settings

**Comment by johnsBeharry** [comment]
dammn. 🔥🔥🔥

**Comment by ConorOkus** [comment]
Looking good man!

**Comment by reez** [comment]
Thanks for pumping me up @johnsBeharry @ConorOkus 🙏

**Comment by reez** [comment]
mm-single

Single Bed Setup

**Comment by reez** [comment]
mm-double


Double Bed Setup

**Comment by reez** [comment]
Transactions
mm-transaction

Login
mm-login

**Comment by reez** [comment]
mm-receive
Receive

**Comment by reez** [comment]
Multisig Recovery
mm-multisig-recovery

Multisig Send
mm-multisig-send

**Comment by reez** [comment]
WalletUI now includes everything in the MyMattress flow, except "Coldcard import" previews.

**Pull request merged**
